name: 080-reusable-workflow-caller

on:
 push:
   branchs: none # [ main ]
 pull_request:
   branchs: none # [ main ]

 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

jobs:
   call-workflow-A:
     uses: devopscypher/github-actions-reusable/.github/workflows/080-reusable-workflow-caller.yaml@main
     with:
       username: USERNAME
     secrets:
      token: ${{ secrets.TOKEN }}

   call-workflow-B:
     uses: devopscypher/github-actions-reusable/.github/workflows/080-reusable-workflow-caller.yaml@main
     with:
       username: USERNAME
     secrets:
      token: ${{ secrets.TOKEN }}   
